### ISSUE TITLE
pprof.Trace() does not implemented golang v1.4.2

### ISSUE THREAD

**Issue by evalphobia** [revel/modules#14]
`pprof.Trace()` seems to be not implemented yet v1.4.2 ([pprof](https://golang.org/pkg/net/http/pprof/))

so when use this module, I got error below

```
github.com/revel/modules/pprof/app/controllers/pprof.go:34: undefined: "net/http/pprof".Trace
```

`pprof.Trace()` is [merged on Jan 29, 2015](https://github.com/golang/go/commits/master/src/net/http/pprof/pprof.go)
It is convenient to remove `PprofHandler.Trace()` untill this feature supported on the next stable Go version (v1.4.3 or v1.5?).

**Comment by brendensoares** [comment]
@evalphobia could you submit a PR with your proposed changes?

**Comment by notzippy** [comment]
See #20  as well

**Comment by notzippy** [comment]
It is implemented in go1.6
