### ISSUE TITLE
error while parsing profile: unrecognized profile format

### ISSUE THREAD

**Issue by victoryfun** [revel/modules#20]
Hi,
    While I'm trying to get the heap profile with 

> go tool pprof http://localhost:9000/debug/pprof/heap.
It got a error. See as following snapshot.
![image](https://cloud.githubusercontent.com/assets/17764306/21519641/db615fca-cd29-11e6-8978-9cfc29cdbf62.png)

**Comment by notzippy** [comment]
For module see https://github.com/revel/revel/pull/424

**Comment by notzippy** [comment]
It appears this is merged in already, if it continues to be an issue please reopen
